/// @description Insert description here
// You can write your code in this editor

credits_text = [
    "1. Roteiro Principal",
    "1.1 Começo",
    "Noite 01:",
    "A história começa de dia em uma vila deserta devido a uma tempestade.",
    "Será feito 1 quadro (medida utilizada para contar a passagem do tempo",
    "dentro da história) destinado às especificações de botões do jogo,",
    "o tutorial e funcionalidades. Ming carregará um lampião contendo a",
    "Aura, que é usado para iluminar o cenário escuro fora das construções.",
    "A alguns dias Ming vem percebendo uma mudança no mundo,",
    "o fato de que os dias começaram a ficar mais curtos, nas últimas",
    "semanas os dias duraram apenas 10 horas. Ming fala com Aura sobre",
    "esses acontecimentos estranhos, onde Aura indica ir atrás de alguém",
    "do vilarejo que tenha alguma resposta. Ming e Aura decidem então,",
    "ir até a igreja, por estar iluminada e com a porta entreaberta.",
    "Após entrar na igreja Ming encontra Freixa, uma lagartixa freira",
    "que estava rezando para uma das representações do Deus do Equilíbrio",
    "(Ming), onde Ming questiona Freixa sobre as coisas acontecendo no",
    "mundo atualmente. Freixa fala sobre uma escuridão vinda do leste,",
    "dominando cada vez mais o mundo mortal e como as criaturas estão",
    "cada vez mais aterrorizadas sobre tudo isso.",
    "Então, quando Ming sai da igreja, ele tem um diálogo com Aura,",
    "onde eles recordam os conhecimentos da expedição que já haviam",
    "adquirido, e lembram-se das ruínas escondidas ao leste de blablabla.",
    "Prontamente, Ming começa sua jornada em direção às ruínas ao leste.",
    " ",
    "1.2 Meio",
    "Noite 02:",
    "Primeiro quadro: A caminho do leste, Ming entra numa floresta de taiga,",
    "com um caminho estreito entre a vegetação. A noite estava se aproximando,",
    "mesmo que fosse apenas 2 horas da tarde. A partir desse momento,",
    "será contada a primeira noite de dificuldade do jogo. O céu terá",
    "cores alternadas a cada noite contabilizada, evidenciando a dificuldade",
    "das fases. O céu irá gradativamente ganhando cores mais escuras,",
    "indo de tons azulados e roxos até próximo a um tom de preto.",
    "Nessa segunda noite, Ming andará no primeiro quadro até uma corrosão,",
    "onde surgirão monstros, Ghouls, vindos do lodo preto ao redor de uma cápsula.",
    "Ming tem um breve diálogo com Aura, pois é perceptível o fato de que",
    "aqueles monstros estavam protegendo algo no centro da corrosão,",
    "como um cristal emitindo um leve brilho. Em seguida à derrota dos",
    "monstros, o cristal é quebrado e aberto, revelando dentro de si",
    "uma chama coletável que aumentará o EXP do personagem e a força de Aura.",
    " ",
    "Segundo quadro: Ming fará uma caminhada pela floresta de taiga,",
    "apreciando o cenário e, possivelmente, poderá interagir com objetos",
    "presentes ali.",
    "Terceiro quadro: Ming andará até outra corrosão, onde aparecerá Ghouls.",
    "Ming irá derrotar os monstros e desbloquear a nova chama que ganhará EXP.",
    "Depois da batalha, enquanto continua sua caminhada, ele se depara com",
    "uma fogueira apagada feita com madeiras e restos de algum tipo de metal",
    "que eles não reconhecem. Eles decidem repousar ali mesmo, por estarem",
    "exaustos das batalhas. Devido ao fato de não terem nada para produzir",
    "fogo na fogueira, Aura decide se tornar chama para ela, se transformando",
    "numa chama violeta. Após interagir com a fogueira, o jogador pode salvar o jogo.",
    "Noite 03:",
    "Depois de Ming acordar, ele continua sua jornada ao leste.",
    "Primeiro quadro: Ele novamente encontra uma corrosão, Ghouls começam",
    "a surgir do lodo novamente, e mais outra criatura que surge da escuridão,",
    "uma Sombra. Mais uma batalha acontece, e Ming captura mais uma chama.",
    "Segundo quadro: Ming anda pela floresta e interage com objetos.",
    "Terceiro quadro: Ming encontra outra corrosão e outra batalha acontece,",
    "e Aura agora pode curar o jogador. Após a batalha ele acha outra",
    "fogueira um pouco mais destruída e decide descansar por ali mesmo.",
    "Mais um save é feito.",
    " ",
    "Noite 04",
    "Primeiro quadro: Cada dia que passa, cada vez mais Ming se aprofunda",
    "na noite, o sol não sobe há 3 dias. Ming continua sua jornada ao leste.",
    "Ele encontra mais uma corrosão, e mais uma batalha com Ghouls e Sombras",
    "acontecem, cada vez mais difícil.",
    "Segundo quadro: Após isso ele continua se aprofundando na noite e",
    "na escuridão. Durante o caminho, Aura e Ming sentem a sensação de",
    "estarem cada vez mais perto do perigo, uma sensação inquietante.",
    "Blocos de pedras jogados pelo chão mostram que eles estão próximos",
    "às ruínas. Eles encontram um arco, o que uma vez poderia ter sido",
    "a entrada de uma grande torre. Ming para por alguns segundos, se",
    "questionando se o que encontraria lá dentro, depois de derrotado,",
    "poderia levá-lo de volta para seu antigo lar, ou se seu destino",
    "seria selado ali mesmo e ele nunca mais poderia ver o sol nascer ao leste.",
    "Depois de ponderar, Ming decide tomar coragem e passar o arco,",
    "seguindo em direção à última batalha.",
    "Terceiro quadro: Dentro da torre, ainda é possível observar o céu",
    "noturno, já sem nenhuma estrela nele. E então, Ming se depara com a",
    "criatura que causou tudo isso, a quem ele já teve contato antes, um",
    "dos antigos deuses que vivia junto a ele e muitos outros, o qual a",
    "ganância e busca por poder nunca cessaram.",
    "Mesmo após ser expulso do céu, ele continuou sua jornada em busca de",
    "poder e ainda mais amargurado por ter sido deixado de lado pelos",
    "outros deuses. Ming nunca soube o destino que ele levará após ser",
    "expulso do céu, tudo que ele sabia é que Umbra não teve um começo",
    "tão diferente do dele, a busca por uma justiça falha que não levaria",
    "em nada o transformou em uma criatura dominada pelo ódio.",
    "E em vez de se redimir perante seus atos, ele apenas continuou em busca",
    "de uma vingança contra aqueles que foram contra suas ideias.",
    "Então, após um diálogo com Umbra, eles decidem acabar com isso de uma vez.",
    "A batalha acontece.",
    " ",
    "1.3 Fim"
];


scroll_speed = 0.5;
text_position_y = room_height;
text_spacing = 32;
font = fnt_escritasdecifraveis;
